# frozen_string_literal: true

# This file is generated by render.sh, do not edit manually.
class ${class_name} < Formula
  desc '${description}'
  homepage '${homepage}'
  version '${version}'
  license 'MIT'

  on_macos do
    if Hardware::CPU.intel?
      url 'https://github.com/${repo_owner}/${PKG_REPO}/releases/download/v${version}/${PKG_REPO}-darwin-amd64.tar.gz'
      sha256 '${darwin_amd64_sha256}'

      def install
        bin.install '${PKG_REPO}'
      end
    end
    if Hardware::CPU.arm?
      url 'https://github.com/${repo_owner}/${PKG_REPO}/releases/download/v${version}/${PKG_REPO}-darwin-arm64.tar.gz'
      sha256 '${darwin_arm64_sha256}'

      def install
        bin.install '${PKG_REPO}'
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url 'https://github.com/${repo_owner}/${PKG_REPO}/releases/download/v${version}/${PKG_REPO}-linux-amd64.tar.gz'
      sha256 '${linux_amd64_sha256}'

      def install
        bin.install '${PKG_REPO}'
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url 'https://github.com/${repo_owner}/${PKG_REPO}/releases/download/v${version}/${PKG_REPO}-linux-arm64.tar.gz'
      sha256 '${linux_arm64_sha256}'

      def install
        bin.install '${PKG_REPO}'
      end
    end
  end

  test do
    system "#{bin}/${PKG_REPO} version"
  end
end
