name: "Rubocop formula"
description: "Run rubocop on the render formula"

runs:
  using: "composite"
  steps:
    - name: Install envsbust
      uses: anttiharju/actions/install-envsubst@v0
    - name: Render out final formula
      shell: sh
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        ./pkgs/render.sh brew
    - name: Output name with underscores
      id: underscore
      uses: ./.github/actions/underscore-name
    - uses: anttiharju/actions/rubocop-file@v0
      with:
        file: "pkgs/brew/${{ steps.underscore.outputs.filename }}.rb"
