name: "Rubocop formula"
description: "Run rubocop on the render formula"

runs:
  using: "composite"
  steps:
    - name: Render out final formula
      shell: sh
      run: |
        ./dist/brew/render.bash
    - uses: anttiharju/actions/rubocop-file@v1
      with:
        file: "dist/brew/.${{ github.event.repository.name }}.rb"
