name: "Rubocop formula"
description: "Run rubocop on the render formula"

runs:
  using: "composite"
  steps:
    - name: Render out final formula
      shell: sh
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        ./.release/render.sh brew
    - name: Output name with underscores
      id: underscore
      uses: ./.github/actions/underscore-name
    - name: rubocop
      shell: sh
      env:
        filename: ${{ steps.underscore.outputs.filename }}
      run: |
        rubocop ".release/brew/$filename.rb"
