name: "Rubocop formula"
description: "Run rubocop on the render formula"

runs:
  using: "composite"
  steps:
    - name: Render out final formula
      shell: sh
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        ./pkgs/render.sh brew
    - uses: anttiharju/actions/rubocop-file@v0
      with:
        file: "pkgs/brew/${{ github.event.repository.name }}.rb"
