name: "Commit release"
description: "Creates a release commit"
inputs:
  version:
    description: "Release version"
    required: true
  ANTTIHARJU_BOT_ID:
    description: "GitHub App ID for committing the release"
    required: true
  ANTTIHARJU_BOT_PRIVATE_KEY:
    description: "GitHub App private key for committing the release"
    required: true

runs:
  using: "composite"
  steps:
    - name: Generate commit token
      uses: actions/create-github-app-token@v1
      id: generate
      with:
        app-id: ${{ inputs.ANTTIHARJU_BOT_ID }}
        private-key: ${{ inputs.ANTTIHARJU_BOT_PRIVATE_KEY }}
        repositories: ${{ github.event.repository.name }}
    - name: Checkout
      uses: actions/checkout@v6
      with:
        token: ${{ steps.generate.outputs.token }}
        path: release
    - name: Get pull request number
      id: pr
      shell: sh
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        pr_number="$(gh api "repos/$GITHUB_REPOSITORY/commits/$GITHUB_SHA/pulls" --jq '.[0].number')"
        echo "number=$pr_number" >> "$GITHUB_OUTPUT"
    - name: Commit changes
      uses: anttiharju/actions/commit-changes@v0
      with:
        author: "${{ github.actor }}[bot]"
        committer: "${{ github.actor }}[bot]"
        message: "${{ inputs.version }}${{ steps.pr.outputs.number && format(' #{0}', steps.pr.outputs.number) || '' }}"
        working-directory: release
