name: Release
description: 'Release a binary'

runs:
  using: 'composite'
  steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Build binary
      shell: sh
      run: make build
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: vmatch-golangci-lint-${{ runner.os }}-${{ runner.arch }}
        path: bin/vmatch-golangci-lint
