name: Publish docs
description: Publishes the documentation to GitHub Pages with mkdocs gh-deploy.

runs:
  using: "composite"
  steps:
    - shell: sh
      run: |
        pip install mkdocs
    - shell: sh
      env:
        GIT_COMMITTER_NAME: "github-actions[bot]"
        GIT_COMMITTER_EMAIL: "github-actions[bot]@users.noreply.github.com"
        GIT_AUTHOR_NAME: "${{ github.actor }}"
        GIT_AUTHOR_EMAIL: "${{ github.actor }}@users.noreply.github.com"
      run: |
        mkdocs gh-deploy --force --no-history
