name: Publish docs
description: Publishes the documentation to GitHub Pages with mkdocs gh-deploy.

runs:
  using: "composite"
  steps:
    - shell: sh
      env:
        GIT_COMMITTER_NAME: "anttiharju[bot]"
        GIT_COMMITTER_EMAIL: "anttiharju[bot]@users.noreply.github.com" 
      run: |
        pip install mkdocs
        mkdocs gh-deploy --force --no-history
