name: "Detect changes"
description: "Combines find-changes with the relevant check-lefthook-glob steps"
runs:
  using: "composite"
  steps:
    - name: Find changes
      id: changed
      uses: anttiharju/actions/find-changes@v0
    - name: Check if binary has changed
      id: binary
      uses: anttiharju/actions/check-lefthook-glob@v0
      with:
        changes: ${{ steps.changed.outputs.files }}
        yq: '.pre-commit.jobs[] | select(.name == "Binary") | .glob'
    - name: Check if distributions have changed
      id: distributions
      uses: anttiharju/actions/check-lefthook-glob@v0
      with:
        changes: ${{ steps.changed.outputs.files }}
        yq: '.pre-commit.jobs[] | select(.name == "Homebrew formula") | .glob'
    - name: Check if documentation has changed
      id: documentation
      uses: anttiharju/actions/check-lefthook-glob@v0
      with:
        changes: ${{ steps.changed.outputs.files }}
        yq: '.pre-commit.jobs[] | select(.name == "Documentation") | .glob'
    - name: Check if Go code has changed
      id: go_code
      uses: anttiharju/actions/check-lefthook-glob@v0
      with:
        changes: ${{ steps.changed.outputs.files }}
        yq: '.pre-commit.jobs[] | select(.name == "Go code") | .glob'
    - name: Check if GitHub Actions have changed
      id: github_actions
      uses: anttiharju/actions/check-lefthook-glob@v0
      with:
        changes: ${{ steps.changed.outputs.files }}
        yq: '.pre-commit.jobs[] | select(.name == "GitHub Actions") | .glob'
    - name: Check if GitHub Actions Workflows have changed
      id: github_actions_workflows
      uses: anttiharju/actions/check-lefthook-glob@v0
      with:
        changes: ${{ steps.changed.outputs.files }}
        yq: '.pre-commit.jobs[] | select(.name == "GitHub Actions Workflows") | .glob'
    - name: Check if scripts have changed
      id: scripts
      uses: anttiharju/actions/check-lefthook-glob@v0
      with:
        changes: ${{ steps.changed.outputs.files }}
        yq: '.pre-commit.jobs[] | select(.name == "Scripts") | .glob'
    - name: Markdown and YAML
      id: markdown_and_yaml
      uses: anttiharju/actions/check-lefthook-glob@v0
      with:
        changes: ${{ steps.changed.outputs.files }}
        yq: '.pre-commit.jobs[] | select(.name == "Markdown and YAML") | .glob'
outputs:
  binary_changed:
    description: "Whether binary has changed"
    value: ${{ steps.binary.outputs.changed }}
  distributions_changed:
    description: "Whether distributions have changed"
    value: ${{ steps.distributions.outputs.changed }}
  documentation_changed:
    description: "Whether documentation has changed"
    value: ${{ steps.documentation.outputs.changed }}
  go_code_changed:
    description: "Whether Go code has changed"
    value: ${{ steps.go_code.outputs.changed }}
  github_actions_changed:
    description: "Whether GitHub Actions have changed"
    value: ${{ steps.github_actions.outputs.changed }}
  github_actions_workflows_changed:
    description: "Whether GitHub Actions Worfklows have changed"
    value: ${{ steps.github_actions_workflows.outputs.changed }}
  scripts_changed:
    description: "Whether scripts have changed"
    value: ${{ steps.scripts.outputs.changed }}
  markdown_and_yaml_changed:
    description: "Whether Markdown and YAML have changed"
    value: ${{ steps.markdown_and_yaml.outputs.changed }}
