name: "Detect changes"
description: "Decide what steps need running based on changes"
inputs:
  changes:
    description: "JSON array of changed files"
    required: true
runs:
  using: "composite"
  steps:
    - id: github_actions_workflows
      uses: anttiharju/actions/compare-changes@v0
      with:
        wildcard: actionlint
        changes: ${{ inputs.changes }}
    - id: binary
      uses: anttiharju/actions/compare-changes@v0
      with:
        wildcard: go-binary
        changes: ${{ inputs.changes }}
    - id: go_code
      uses: anttiharju/actions/compare-changes@v0
      with:
        wildcard: golangci-lint
        changes: ${{ inputs.changes }}
    - id: dist_brew
      uses: anttiharju/actions/compare-changes@v0
      with:
        wildcard: dist-brew
        changes: ${{ inputs.changes }}
    - id: dist_github
      uses: anttiharju/actions/compare-changes@v0
      with:
        wildcard: dist-github
        changes: ${{ inputs.changes }}
    - id: documentation
      uses: anttiharju/actions/compare-changes@v0
      with:
        wildcard: mkdocs
        changes: ${{ inputs.changes }}
    - id: md_and_yml
      uses: anttiharju/actions/compare-changes@v0
      with:
        wildcard: prettier
        changes: ${{ inputs.changes }}
    - id: scripts
      uses: anttiharju/actions/compare-changes@v0
      with:
        wildcard: shellcheck
        changes: ${{ inputs.changes }}
outputs:
  github_actions_workflows:
    description: "Whether GitHub Actions workflows have changed"
    value: ${{ steps.github_actions_workflows.outputs.changed }}
  binary:
    description: "Whether the binary has changed"
    value: ${{ steps.binary.outputs.changed }}
  go_code:
    description: "Whether Go code has changed"
    value: ${{ steps.go_code.outputs.changed }}
  dist_brew:
    description: "Whether Brew distribution has changed"
    value: ${{ steps.dist_brew.outputs.changed }}
  dist_github:
    description: "Whether GitHub distribution has changed"
    value: ${{ steps.dist_github.outputs.changed }}
  documentation:
    description: "Whether documentation has changed"
    value: ${{ steps.documentation.outputs.changed }}
  md_and_yml:
    description: "Whether Markdown or YAML has changed"
    value: ${{ steps.md_and_yml.outputs.changed }}
  scripts:
    description: "Whether scripts have changed"
    value: ${{ steps.scripts.outputs.changed }}
