name: Validate docs
description: Runs mkdocs build with strict mode so any mistakes are caught early.

runs:
  using: "composite"
  steps:
    - shell: sh
      run: |
        pip install mkdocs
        mkdocs build --strict
