name: "Get Version"
description: "Gets the latest release version via values.bash"
runs:
  using: "composite"
  steps:
    - name: Get Version
      id: get-version
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      # This way we get shellcheck validations in case of file renames
      run: |
        "$GITHUB_ACTION_PATH/action.bash" >> "$GITHUB_OUTPUT"
outputs:
  version:
    description: "The latest release version"
    value: ${{ steps.get-version.outputs.version }}
