name: "Find changes"
description: "This composite action enables running check-changes in pull requests to benefit for example from its yq input validation"
inputs:
  force-all:
    required: false
    description: "Force all checks to run"
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Find changes
      id: changed
      uses: anttiharju/actions/find-changes@v0
    - name: Check if binary has changed
      id: binary
      uses: anttiharju/actions/check-changes@v0
      with:
        changes: ${{ steps.changed.outputs.files }}
        file: lefthook.yml
        yq: '.pre-commit.jobs[] | select(.name == "Binary") | .glob'
        force-true: ${{ inputs.force-all }}
    - name: Check if distributions have changed
      id: distributions
      uses: anttiharju/actions/check-changes@v0
      with:
        changes: ${{ steps.changed.outputs.files }}
        file: lefthook.yml
        yq: '.pre-commit.jobs[] | select(.name == "Homebrew formula") | .glob'
        force-true: ${{ inputs.force-all }}
    - name: Check if documentation has changed
      id: documentation
      uses: anttiharju/actions/check-changes@v0
      with:
        changes: ${{ steps.changed.outputs.files }}
        file: lefthook.yml
        yq: '.pre-commit.jobs[] | select(.name == "Documentation") | .glob'
        force-true: ${{ inputs.force-all }}
    - if: github.event_name != 'push' || inputs.force-all == 'true'
      name: Check if Go code has changed
      id: go_code
      uses: anttiharju/actions/check-changes@v0
      with:
        changes: ${{ steps.changed.outputs.files }}
        file: lefthook.yml
        yq: '.pre-commit.jobs[] | select(.name == "Go code") | .glob'
        force-true: ${{ inputs.force-all }}
    - if: github.event_name != 'push' || inputs.force-all == 'true'
      name: Check if GitHub Actions have changed
      id: github_actions
      uses: anttiharju/actions/check-changes@v0
      with:
        changes: ${{ steps.changed.outputs.files }}
        file: lefthook.yml
        yq: '.pre-commit.jobs[] | select(.name == "GitHub Actions") | .glob'
        force-true: ${{ inputs.force-all }}
    - if: github.event_name != 'push' || inputs.force-all == 'true'
      name: Check if GitHub Actions Workflows have changed
      id: github_actions_workflows
      uses: anttiharju/actions/check-changes@v0
      with:
        changes: ${{ steps.changed.outputs.files }}
        file: lefthook.yml
        yq: '.pre-commit.jobs[] | select(.name == "GitHub Actions Workflows") | .glob'
        force-true: ${{ inputs.force-all }}
    - if: github.event_name != 'push' || inputs.force-all == 'true'
      name: Check if scripts have changed
      id: scripts
      uses: anttiharju/actions/check-changes@v0
      with:
        changes: ${{ steps.changed.outputs.files }}
        file: lefthook.yml
        yq: '.pre-commit.jobs[] | select(.name == "Scripts") | .glob'
        force-true: ${{ inputs.force-all }}
    - if: github.event_name != 'push' || inputs.force-all == 'true'
      name: Markdown and YAML
      id: markdown_and_yaml
      uses: anttiharju/actions/check-changes@v0
      with:
        changes: ${{ steps.changed.outputs.files }}
        file: lefthook.yml
        yq: '.pre-commit.jobs[] | select(.name == "Markdown and YAML") | .glob'
        force-true: ${{ inputs.force-all }}
outputs:
  binary_changed:
    description: "Whether binary has changed"
    value: ${{ steps.binary.outputs.changed }}
  distributions_changed:
    description: "Whether distributions have changed"
    value: ${{ steps.distributions.outputs.changed }}
  documentation_changed:
    description: "Whether documentation has changed"
    value: ${{ steps.documentation.outputs.changed }}
  go_code_changed:
    description: "Whether Go code has changed"
    value: ${{ steps.go_code.outputs.changed }}
  github_actions_changed:
    description: "Whether GitHub Actions have changed"
    value: ${{ steps.github_actions.outputs.changed }}
  github_actions_workflows_changed:
    description: "Whether GitHub Actions Worfklows have changed"
    value: ${{ steps.github_actions_workflows.outputs.changed }}
  scripts_changed:
    description: "Whether scripts have changed"
    value: ${{ steps.scripts.outputs.changed }}
  markdown_and_yaml_changed:
    description: "Whether Markdown and YAML have changed"
    value: ${{ steps.markdown_and_yaml.outputs.changed }}
