name: GitHub Actions
on:
  pull_request:
    paths:
      - '.github/**'

# This is a separate workflow from vmatch.yml as CI
# is expected to remain largely static across PRs.
jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: action-validator
        uses: anttiharju/actions/action-validator@v0

      - if: always()
        name: actionlint
        uses: anttiharju/actions/actionlint@v0
