name: Distribute
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      ANTTIHARJU_BOT_ID:
        required: true
      ANTTIHARJU_BOT_PRIVATE_KEY:
        required: true

permissions:
  contents: write

jobs:
  build-bottles:
    name: Build bottle
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Checkout
        uses: actions/checkout@v4

      # required by values.bash through render.bash
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Create a local tap
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          ./dist/brew/render.bash --tap
          git add --all
          git commit -m "Render formula to build ${{ runner.os }} bottle"
          brew tap anttiharju/vmatch file://${{ github.workspace }}

      - name: Build bottle
        run: |
          brew install --build-bottle vmatch
          brew bottle vmatch

      - name: Upload bottle to GitHub release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          find . -maxdepth 1 -name 'vmatch--*.bottle.*.tar.gz' -exec gh release upload build95 {} \;

  update-homebrew-tap:
    name: Update homebrew-tap
    needs: build-bottles
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate commit token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.ANTTIHARJU_BOT_ID }}
          private-key: ${{ secrets.ANTTIHARJU_BOT_PRIVATE_KEY }}
          repositories: homebrew-tap
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: anttiharju/homebrew-tap
          token: ${{ steps.generate-token.outputs.token }}
          path: homebrew-tap
      - name: Setup tag environment variable for values.bash
        env:
          tag: ${{ inputs.tag }}
        run: echo "tag=$tag" >> "$GITHUB_ENV"
      - name: Render formula template
        uses: anttiharju/actions/render-template@v0
        with:
          template: dist/brew/template.rb
          values: dist/brew/values.bash
          output: homebrew-tap/Formula/${{ github.event.repository.name }}.rb
      - name: Commit changes
        uses: anttiharju/actions/commit-changes@v0
        with:
          committer: "anttiharju[bot]"
          message: |
            Update vmatch formula to ${{ inputs.tag }}

            https://github.com/anttiharju/vmatch/blob/${{ github.sha }}/.github/workflows/distribute.yml
          working-directory: homebrew-tap
