name: Go
on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: anttiharju/actions/lint-go@v0
        with:
          version-file: ".golangci-version"

      - if: always()
        name: go build
        uses: ./.github/actions/build
