name: Lint
on:
  push:
    branches:
      - main
    paths:
      - '**.go'
  pull_request:
    paths:
      - '**.go'

permissions:
  contents: read

jobs:
  golangci-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: .github/scripts/golangci-lint-version.sh
      - uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
