name: Labels

on:
  pull_request:
    # opened, synchronize, and reopened are the defaults per https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
    types: [opened, synchronize, reopened, labeled]

jobs:
  check:
    name: Check
    runs-on: ubuntu-24.04
    steps:
      - name: Require semantic version label
        uses: anttiharju/actions/require-semver@v0
