name: Main Push
on:
  push:
    branches: main

permissions:
  contents: write

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate.yml

  release:
    name: Release
    needs: validate
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: anttiharju/actions/release@v0
      - name: Extract details
        id: extract-details
        uses: ./.github/actions/extract-details
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
    outputs:
      homepage: ${{ steps.extract-details.outputs.homepage }}
      url: ${{ steps.extract-details.outputs.url }}
      go_version: ${{ steps.extract-details.outputs.go_version }}
      version: ${{ steps.extract-details.outputs.version }}

  update-distributions:
    name: Update distributions
    needs: release
    uses: ./.github/workflows/update_dists.yml
    with:
      homepage: ${{ needs.release.outputs.homepage }}
      url: ${{ needs.release.outputs.url }}
      go-version: ${{ needs.release.outputs.go_version }}
      version: ${{ needs.release.outputs.version }}
    secrets: inherit
