name: Main Push
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate.yml

  release:
    name: Release
    needs: validate
    runs-on: ubuntu-24.04
    steps:
      - name: Release
        uses: anttiharju/actions/release@v0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: false # To suppress warning about 'missing' go sum
      - name: Extract details
        id: extract-details
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          {
            echo "homepage=$(gh api repos/${{ github.repository }} --jq .homepage)"
            echo "url=$(gh api repos/${{ github.repository }}/releases/latest --jq .tarball_url)"
            echo "go_version=$(go list -m -f '{{.GoVersion}}')"
          } >> "$GITHUB_OUTPUT"
      - uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.AUTOMATION_APP_ID }}
          private-key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}
    outputs:
      homepage: ${{ steps.extract-details.outputs.homepage }}
      url: ${{ steps.extract-details.outputs.url }}
      go_version: ${{ steps.extract-details.outputs.go_version }}
      token: ${{ steps.generate-token.outputs.token }}

  homebrew-tap:
    name: Homebrew tap
    needs: release
    uses: ./.github/workflows/homebrew_tap.yml
    with:
      homepage: ${{ needs.release.outputs.homepage }}
      url: ${{ needs.release.outputs.url }}
      go_version: ${{ needs.release.outputs.go_version }}
    secrets:
      token: ${{ needs.release.outputs.token }}
