name: Main Push
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate.yml

  release:
    name: Release
    needs: validate
    runs-on: ubuntu-24.04
    steps:
      - name: Release
        uses: anttiharju/actions/release@v0
