name: Main Push
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    needs: test
    runs-on: ubuntu-24.04
    steps:
      - name: Release
        uses: anttiharju/actions/release@v0
