name: Main Push
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    needs: test
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: false # To suppress warning about 'missing' go sum
      - name: Build binary
        run: make build
      - name: Release
        uses: ./.github/actions/release
        with:
          binary: bin/vmatch-golangci-lint
