name: Main Push
on:
  push:
    branches: main

permissions:
  contents: write

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate.yml

  release:
    name: Release
    needs: validate
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: anttiharju/actions/release@v0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: false # To suppress warning about 'missing' go sum
      - name: Extract details
        id: extract-details
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          {
            url=$(gh api repos/${{ github.repository }}/releases/latest --jq .tarball_url)
            echo "homepage=$(gh api repos/${{ github.repository }} --jq .homepage)"
            echo "url=$url"
            echo "go_version=$(go list -m -f '{{.GoVersion}}')"
            echo "version=$(basename "$url")" >> "$GITHUB_OUTPUT"
          } >> "$GITHUB_OUTPUT"
    outputs:
      homepage: ${{ steps.extract-details.outputs.homepage }}
      url: ${{ steps.extract-details.outputs.url }}
      go_version: ${{ steps.extract-details.outputs.go_version }}
      version: ${{ steps.extract-details.outputs.version }}

  homebrew-tap:
    name: Homebrew tap
    needs: release
    uses: ./.github/workflows/homebrew_tap.yml
    with:
      homepage: ${{ needs.release.outputs.homepage }}
      url: ${{ needs.release.outputs.url }}
      go-version: ${{ needs.release.outputs.go_version }}
      version: ${{ needs.release.outputs.version }}
    secrets: inherit
