name: Main Push
on:
  push:
    branches: main

permissions:
  contents: write

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate.yml

  release:
    name: Release
    needs: validate
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: vmatch
      - name: Release
        uses: anttiharju/actions/release@v0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: false # To suppress warning about 'missing' go sum
      - name: Extract details
        id: extract-details
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          {
            echo "homepage=$(gh api repos/${{ github.repository }} --jq .homepage)"
            echo "url=$(gh api repos/${{ github.repository }}/releases/latest --jq .tarball_url)"
            echo "go_version=$(go list -m -f '{{.GoVersion}}')"
          } >> "$GITHUB_OUTPUT"

      - name: Generate commit token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.AUTOMATION_APP_ID }}
          private-key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}
          repositories: homebrew-tap
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: anttiharju/homebrew-tap
          token: ${{ steps.generate-token.outputs.token }}
          path: homebrew-tap
      - name: Render formula
        uses: anttiharju/actions/render-formula@v0
        with:
          template: Go
          app-name: ${{ github.event.repository.name }}
          description: Wrapper that automatically calls the golangci-lint version matching your project
          homepage: ${{ steps.extract-details.outputs.homepage }}
          url: ${{ steps.extract-details.outputs.url }}
          go-version: ${{ steps.extract-details.outputs.go_version }}
      - name: Extract version from url
        id: extract-version
        env:
          url: ${{ steps.extract-details.outputs.url }}
        run: echo "version=$(basename "$url")" >> "$GITHUB_OUTPUT"
      - name: Commit changes
        uses: anttiharju/actions/commit-changes@v0
        with:
          message: |
            Update vmatch formula to ${{ steps.extract-version.outputs.version }}

            https://github.com/anttiharju/vmatch/blob/${{ github.sha }}/.github/workflows/homebrew_tap.yml
