name: Main Push
on:
  push:
    branches:
      - main

jobs:
  validate:
    name: Validate
    uses: ./.github/workflows/validate.yml

  release:
    name: Release
    needs: validate
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - name: Generate docs token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.AUTOMATION_APP_ID }}
          private-key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - name: Release vmatch
        uses: anttiharju/actions/release@v0
      - name: Release docs
        uses: anttiharju/actions/release-docs@v0
        with:
          committer: "anttiharju[bot]"
      - name: Get project details
        id: get-project-details
        uses: ./.github/actions/get-project-details
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache: false # Suppress warning about a 'missing' go.sum
    outputs:
      description: ${{ steps.get-project-details.outputs.description }}
      homepage: ${{ steps.get-project-details.outputs.homepage }}
      url: ${{ steps.get-project-details.outputs.url }}
      go_version: ${{ steps.get-project-details.outputs.go_version }}
      version: ${{ steps.get-project-details.outputs.version }}

  distribute:
    name: Distribute
    needs: release
    uses: ./.github/workflows/distribute.yml
    permissions:
      contents: write
    with:
      description: ${{ needs.release.outputs.description }}
      homepage: ${{ needs.release.outputs.homepage }}
      url: ${{ needs.release.outputs.url }}
      go-version: ${{ needs.release.outputs.go_version }}
      version: ${{ needs.release.outputs.version }}
    secrets: inherit
