name: Plan
permissions:
  contents: none
  pull-requests: none
on:
  pull_request:
    # https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#pull_request
    # defaults: opened, synchronize, reopened
    types: [opened, synchronize, reopened, labeled, unlabeled]
    paths:
      - "flake.nix"
      - "flake.lock"

jobs:
  container:
    name: Build CI container
    runs-on: ubuntu-24.04
    permissions:
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-25.05
      - name: Parse container version
        id: container
        run: |
          version="$(nix eval .#container_version --raw)"
          echo "version=$version" >> "$GITHUB_OUTPUT"
      - name: Output container version
        env:
          container_version: ${{ steps.container.outputs.version }}
        run: |
          echo "$container_version"
      - run: |
          nix build .#ci && ./result | docker load
      - name: Tag image for registry
        id: image
        env:
          version: ${{ steps.container.outputs.version }}
        run: |
          image_id="ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-ci"
          image_id="$(echo "$image_id" | tr '[:upper:]' '[:lower:]')"
          docker tag "ci:$version" "$image_id:$version"
          echo "id=$image_id" >> "$GITHUB_OUTPUT"
      - name: Log in to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        env:
          image_id: ${{ steps.image.outputs.id }}
          version: ${{ steps.container.outputs.version }}
        run: |
          docker push "$image_id:$version"
    outputs:
      image: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}-ci:${{ steps.container.outputs.version }}

  validate:
    name: Validate
    needs: container
    uses: ./.github/workflows/validate.yml
    permissions:
      contents: none
      pull-requests: none
    with:
      container: ${{ needs.container.outputs.image }}
