name: Pull Request
on:
  pull_request


jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml

  release:
    name: Release
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: ./.github/actions/release
