name: Test
on:
  workflow_call:

jobs:
  golangci-lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: .github/scripts/golangci-lint-version.sh
      - uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}

  shellcheck:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: scripts/shellcheck.sh

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - run: make test
