name: Validate
on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: golangci-lint
        uses: ./.github/actions/lint

      - if: always()
        name: go build
        uses: ./.github/actions/build

      - if: always()
        name: actionlint
        uses: anttiharju/actions/actionlint@v0

      - if: always()
        name: action-validator
        uses: anttiharju/actions/action-validator@v0
