name: Validate
on:
  workflow_call:

# also update lefthook.yml
jobs:
  vmatch:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        uses: anttiharju/actions/build-go@v0
        with:
          cache: false # Suppress warning about a 'missing' go.sum

      - if: always()
        name: Lint
        uses: anttiharju/actions/lint-go@v0
        with:
          version-file: ".golangci-version"

      - if: always()
        name: Actions
        uses: anttiharju/actions/lint-actions@v0

      - if: always()
        name: Docs
        uses: anttiharju/actions/lint-docs@v0

      - if: always()
        name: Prettier
        uses: anttiharju/actions/prettier@v0
