on:
  pull_request:
  workflow_call:

# Match to lefthook.yml
jobs:
  planner:
    name: Planner
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Find changes
        id: changed
        uses: anttiharju/actions/find-changes@v0
      - name: Check if release has changed
        id: release
        uses: anttiharju/actions/check-changes@v0
        with:
          changes: ${{ steps.changed.outputs.files }}
          file: lefthook.yml
          yq: '.pre-commit.jobs[] | select(.name == "go build") | .glob'
      - name: Check if distribution has changed
        id: distribution
        uses: anttiharju/actions/check-changes@v0
        with:
          changes: ${{ steps.changed.outputs.files }}
          file: lefthook.yml
          yq: '.pre-commit.jobs[] | select(.name == "Brew formula") | .glob'
      - name: Check if documentation has changed
        id: documentation
        uses: anttiharju/actions/check-changes@v0
        with:
          changes: ${{ steps.changed.outputs.files }}
          file: lefthook.yml
          yq: '.pre-commit.jobs[] | select(.name == "MkDocs  strict") | .glob'
    outputs:
      release: ${{ steps.release.outputs.has_changed }}
      distribute: ${{ steps.distribution.outputs.has_changed }}
      publish: ${{ steps.documentation.outputs.has_changed }}

  validate:
    name: Validate
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: go build
        uses: anttiharju/actions/go-build@v0

      - if: always()
        name: golangci-lint
        uses: anttiharju/actions/golangci-lint@v0

      - if: always()
        name: action-validator
        uses: anttiharju/actions/action-validator@v0

      - if: always()
        name: actionlint
        uses: anttiharju/actions/actionlint@v0

      - if: always()
        name: ShellCheck
        uses: anttiharju/actions/shellcheck@v0

      - if: always()
        name: Prettier
        uses: anttiharju/actions/prettier@v0

      - if: always()
        name: EditorConfig-Checker
        uses: anttiharju/actions/editorconfig-checker@v0

      - if: always()
        name: check-relative-markdown-links
        uses: anttiharju/actions/check-relative-markdown-links@v0

      - if: always()
        name: MkDocs build strict
        uses: anttiharju/actions/mkdocs-build-strict@v0
