name: Validate
on:
  workflow_call:
    secrets:
      AUTOMATION_APP_ID:
        required: true
      AUTOMATION_APP_PRIVATE_KEY:
        required: true

jobs:
  vmatch:
    runs-on: ubuntu-24.04
    steps:
      - name: Generate docs token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: ${{ secrets.AUTOMATION_APP_ID }}
          private-key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: golangci-lint
        uses: anttiharju/actions/lint-go@v0
        with:
          version-file: ".golangci-version"

      - if: always()
        name: go build
        uses: ./.github/actions/build

      - name: Publish docs
        uses: ./.github/actions/publish-docs
