on:
  pull_request:
  workflow_call:

# Match to lefthook.yml
jobs:
  validate:
    name: Validate
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find changes
        id: find_changes
        uses: ./.github/actions/find-changes

      - if: always() && steps.find_changes.outputs.release_has_changed == 'true'
        name: go build
        uses: anttiharju/actions/go-build@v0

      - if: always()
        name: golangci-lint
        uses: anttiharju/actions/golangci-lint@v0

      - if: always()
        name: action-validator
        uses: anttiharju/actions/action-validator@v0

      - if: always()
        name: actionlint
        uses: anttiharju/actions/actionlint@v0

      - if: always()
        name: ShellCheck
        uses: anttiharju/actions/shellcheck@v0

      - if: always()
        name: Prettier
        uses: anttiharju/actions/prettier@v0

      - if: always()
        name: EditorConfig-Checker
        uses: anttiharju/actions/editorconfig-checker@v0

      - if: always()
        name: check-relative-markdown-links
        uses: anttiharju/actions/check-relative-markdown-links@v0

      - if: always() && steps.find_changes.outputs.documentation_has_changed == 'true'
        name: MkDocs build strict
        uses: anttiharju/actions/mkdocs-build-strict@v0
