name: Validate
on:
  pull_request:
    paths:
      - '.github/**'

jobs:
  actions:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: actionlint
        uses: anttiharju/actions/actionlint@v0

      - if: always()
        name: action-validator
        uses: anttiharju/actions/action-validator@v0
