name: vmatch
on:
  workflow_call:

jobs:
  validate:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: style
        uses: anttiharju/actions/lint-go@v0
        with:
          version-file: ".golangci-version"

      - if: always()
        name: build
        uses: ./.github/actions/build-go

      - if: always()
        name: docs
        uses: ./.github/actions/validate-docs
