on:
  pull_request:
    branches:
      - wildcard
    paths:
      - "dist/brew/**/*"

jobs:
  lefthook-job:
    runs-on: ubuntu-latest
    if: false
    steps:
      # https://github.com/anttiharju/vmatch/issues/137
      - name: Homebrew formula
        run: echo todo
