name: Homebrew formula glob
on:
  pull_request:
    branches:
      - wildcard
    paths:
      - "dist/brew/**/*"

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo "This will never run"
