name: Go build glob
on:
  pull_request:
    branches:
      - wildcard
    paths:
      - "dist/wrap/**/*"
      - "pkg/**/*"
      - "go.mod"
      - "main.go"

jobs:
  do-nothing:
    runs-on: ubuntu-latest
    if: false
    steps:
      - run: echo "This will never run"
