name: Homebrew formula glob
on:
  pull_request:
    branches:
      - wildcard
    paths:
      - "dist/brew/**/*"

jobs:
  lefthook-job:
    runs-on: ubuntu-latest
    if: false
    steps:
      - name: Homebrew formula
        run: echo todo
